[sniffer]
file_path = "../test/samples/srsRAN_octoclock_samprate_2304_10MHz_scscommon_15khz_b200_fdd_n71_pci_1_2phones_onevoicecall_oneyoutube_rntis_4601_4602_5seconds.fc32"
sample_rate = 23040000
frequency = 627750000
nid_1 = 1
ssb_numerology = 0
rf_args = "type=b200,master_clock_rate=23.04e6"


[rnti_tracker]
enabled = true
output_path = "./rnti_log.json"
# format = "json"
format = "json_per_rnti"
# beta = 1.25                        # people-per-device correction factor (check with papers found)
ttl_seconds = 10.0                 # RNTI inactivity expiry (between 10 and 30 seconds)
crnti_only = false                 # log only C-RNTIs for people-counting
emit_period_ms = 1000                 # emit output every N ms (0 to disable)


# [[pdcch]]
# # si_dci_only = true
# use_config_from_mib = true
# dci_sizes_list = [39]
# scrambling_id_start = 1
# scrambling_id_end = 10
# rnti_start = 15000
# rnti_end = 25000
# coreset_interleaving_pattern = "non-interleaved"
# coreset_duration = 2
# AL_corr_thresholds = [0.5, 0.5, 0.5, 0.5, 1]
# num_candidates_per_AL = [8, 4, 4, 1, 0]


[[pdcch]]
coreset_id = 1
# sc offset aligns the BWP to the lowest SC of the BWP
# As there is an offset of 150 KHz between SSB (to the fc we synch) and the DL_ARCFN,
# the CBW is 52 RBs, and our CORESET is 48 RBs, we shift by 150KHz/15KHz + (52-48)*12(sc/RB)/2
# divided by 2 because we are centered around SSB.
subcarrier_offset = 34
num_prbs = 48
numerology = 0
dci_sizes_list = [39]
scrambling_id_start = 1
scrambling_id_end = 10
rnti_start = 15000
rnti_end = 25000
# rnti_start = 17921
# rnti_end = 17922
coreset_interleaving_pattern = "non-interleaved"
coreset_duration = 2
AL_corr_thresholds = [1, 1, 0.5, 1, 1]
num_candidates_per_AL = [0, 0, 4, 0, 0]
# AL_corr_thresholds = [0.5, 0.5, 0.5, 0.5, 1]
# num_candidates_per_AL = [8, 4, 4, 1, 0]
